// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230413122033_RelationshipAndCardinality")]
    partial class RelationshipAndCardinality
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.AccountRoles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("account_nik")
                        .IsRequired()
                        .HasColumnType("char(5)")
                        .HasColumnName("account_nik");

                    b.Property<int>("role_id")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("id");

                    b.HasIndex("account_nik");

                    b.HasIndex("role_id");

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("API.Models.Accounts", b =>
                {
                    b.Property<string>("employee_nik")
                        .HasColumnType("char(5)")
                        .HasColumnName("employee_nik");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.HasKey("employee_nik");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("API.Models.Educations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("degree")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("degree");

                    b.Property<string>("gpa")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gpa");

                    b.Property<string>("major")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("major");

                    b.Property<int>("university_id")
                        .HasColumnType("int")
                        .HasColumnName("university_id");

                    b.HasKey("id");

                    b.HasIndex("university_id");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("API.Models.Employee", b =>
                {
                    b.Property<string>("nik")
                        .HasColumnType("char(5)")
                        .HasColumnName("nik");

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("datetime")
                        .HasColumnName("birthdate");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<int>("gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<DateTime>("hiring_date")
                        .HasColumnType("datetime")
                        .HasColumnName("hiring_date");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_number");

                    b.HasKey("nik");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("API.Models.Profilings", b =>
                {
                    b.Property<string>("employee_nik")
                        .HasColumnType("char(5)")
                        .HasColumnName("employee_nik");

                    b.Property<int>("education_id")
                        .HasColumnType("int")
                        .HasColumnName("education_id");

                    b.HasKey("employee_nik");

                    b.HasIndex("education_id")
                        .IsUnique();

                    b.ToTable("Profilings");
                });

            modelBuilder.Entity("API.Models.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("API.Models.Universities", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("API.Models.AccountRoles", b =>
                {
                    b.HasOne("API.Models.Accounts", "Accounts")
                        .WithMany("AccountRoles")
                        .HasForeignKey("account_nik")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Models.Roles", "Roles")
                        .WithMany("AccountRoles")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Accounts");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("API.Models.Accounts", b =>
                {
                    b.HasOne("API.Models.Employee", "Employee")
                        .WithOne("Accounts")
                        .HasForeignKey("API.Models.Accounts", "employee_nik")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API.Models.Educations", b =>
                {
                    b.HasOne("API.Models.Universities", "Universities")
                        .WithMany("Educations")
                        .HasForeignKey("university_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Universities");
                });

            modelBuilder.Entity("API.Models.Profilings", b =>
                {
                    b.HasOne("API.Models.Educations", "Educations")
                        .WithOne("Profilings")
                        .HasForeignKey("API.Models.Profilings", "education_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.Employee", "Employee")
                        .WithOne("Profilings")
                        .HasForeignKey("API.Models.Profilings", "employee_nik")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Educations");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API.Models.Accounts", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("API.Models.Educations", b =>
                {
                    b.Navigation("Profilings");
                });

            modelBuilder.Entity("API.Models.Employee", b =>
                {
                    b.Navigation("Accounts")
                        .IsRequired();

                    b.Navigation("Profilings")
                        .IsRequired();
                });

            modelBuilder.Entity("API.Models.Roles", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("API.Models.Universities", b =>
                {
                    b.Navigation("Educations");
                });
#pragma warning restore 612, 618
        }
    }
}
